#!/bin/sh
TEMP_DIR=$(mktemp -d)
SJB_HOME=/tmp/sjb

mkdir -p $SJB_HOME/local

# install locals (zsh, vim)
wget -O $TEMP_DIR/local.tar.gz 'https://github.com/kojandy/coding-at-sjb/releases/download/20.05.3/local.tar.gz'
tar -xf $TEMP_DIR/local.tar.gz -C $SJB_HOME/local

# install node
wget -O $TEMP_DIR/node-v12.16.3-linux-x64.tar.gz 'https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.xz'
tar -xf $TEMP_DIR/node-v12.16.3-linux-x64.tar.gz --strip-components=1 -C $SJB_HOME/local

# install dotfiles
DOTFILES=$HOME/.dotfiles
XDG_CONFIG_HOME=$HOME/.config
git clone https://github.com/kojandy/.dotfiles $DOTFILES
$DOTFILES/install/zgen
ln -sf $DOTFILES/profile $HOME/.profile
ln -sf $DOTFILES/vim/vimrc $HOME/.vimrc
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc
mkdir -p $XDG_CONFIG_HOME/git
ln -sf $DOTFILES/git/config $XDG_CONFIG_HOME/git/config
ln -sf $DOTFILES/git/ignore $XDG_CONFIG_HOME/git/ignore

# install st
wget -O $SJB_HOME/local/bin/st 'https://github.com/kojandy/st/releases/download/20.05.1/st'
chmod +x $SJB_HOME/local/bin/st

# map caps lock to control
echo "remove Lock = Caps_Lock
keysym Caps_Lock = Control_L
add Control = Control_L" > $HOME/.xmodmap
xmodmap $HOME/.xmodmap

# set terminal keyboard shortcut
echo "[custom-keybindings/custom0]
binding=['<Super>Return']
command='$SJB_HOME/local/bin/st -e $SJB_HOME/local/bin/zsh'
name='st'
[/]
custom-list=['custom0']" | dconf load /org/cinnamon/desktop/keybindings/

# set .zshrc.local
echo "export PATH=$SJB_HOME/local/bin:$HOME/.dotfiles/bin:\$PATH" > $HOME/.zshrc.local

# execute zsh when bash is executed
echo "exec $SJB_HOME/local/bin/zsh" > $HOME/.bashrc

# clean up
rm -rf $TEMP_DIR
