#!/bin/sh

# install
echo Installing bspwm...
curl -# 'https://raw.githubusercontent.com/kojandy/sjb-pkg-repo/master/bspwm.tar.xz' | tar -xJ --strip-components=1 -C /tmp/sjb/local
echo Installing polybar...
curl -# 'https://raw.githubusercontent.com/kojandy/sjb-pkg-repo/master/polybar.tar.xz' | tar -xJ --strip-components=1 -C /tmp/sjb/local

# copy configs
mkdir -p $HOME/.config/bspwm
mkdir -p $HOME/.config/sxhkd
ln -sf $HOME/coding-at-sjb/config/bspwmrc $HOME/.config/bspwm/bspwmrc
ln -sf $HOME/coding-at-sjb/config/sxhkdrc $HOME/.config/sxhkd/sxhkdrc
ln -sf $HOME/coding-at-sjb/config/polybar $HOME/.config/polybar

# run
export PATH=/tmp/sjb/local/bin:$HOME/.dotfiles/bin:$PATH
export LD_LIBRARY_PATH=/tmp/sjb/local/lib
pkill -x cinnamon
gsettings set org.nemo.desktop show-desktop-icons false
# change background
# gsettings set org.cinnamon.desktop.background picture-uri "file:///"
cd $HOME
setsid bspwm &
