#!/bin/sh

# install
TEMP_DIR=$(mktemp -d)
wget -O $TEMP_DIR/bspwm.tar.xz 'https://github.com/kojandy/coding-at-sjb/releases/download/20.06.2/bspwm.tar.xz'
tar -xf $TEMP_DIR/bspwm.tar.xz -C /tmp/sjb/local
rm -rf $TEMP_DIR

# copy configs
mkdir -p $HOME/.config/bspwm
mkdir -p $HOME/.config/sxhkd
ln -sf $HOME/coding-at-sjb/config/bspwmrc $HOME/.config/bspwm/bspwmrc
ln -sf $HOME/coding-at-sjb/config/sxhkdrc $HOME/.config/sxhkd/sxhkdrc
ln -sf $HOME/coding-at-sjb/config/polybar $HOME/.config/polybar

# run
export PATH=/tmp/sjb/local/bin:$HOME/.dotfiles/bin:$PATH
export LD_LIBRARY_PATH=/tmp/sjb/local/lib
pkill -x cinnamon
gsettings set org.nemo.desktop show-desktop-icons false
# change background
# gsettings set org.cinnamon.desktop.background picture-uri "file:///"
cd $HOME
setsid bspwm &
pkill -QUIT code
