#!/bin/sh
echo "[custom-keybindings/custom0]
binding=['<Super>Return']
command='$HOME/st -e /tmp/sjb/local/bin/zsh'
name='st'

[/]
custom-list=['custom0']" | dconf load /org/cinnamon/desktop/keybindings/
