#!/bin/sh

TEMP_DIR=$(mktemp -d)

cd $TEMP_DIR

wget 'https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.xz'
tar -xf node-v12.16.3-linux-x64.tar.xz
cp -r node-v12.16.3-linux-x64/* ~/.local/

rm -rf $TEMP_DIR
