#!/bin/sh

TEMP_DIR=$(mktemp -d)

cd $TEMP_DIR

git clone -b '3.8' --single-branch --depth 1 'https://github.com/python/cpython'
cd cpython

./configure --prefix=/tmp/sjb/local --enable-shared
make
make install

rm -rf $TEMP_DIR
