#!/bin/sh
SJB_HOME=/tmp/sjb
DOTFILES=$HOME/.dotfiles
XDG_CONFIG_HOME=$HOME/.config
REPO_URL="https://raw.githubusercontent.com/kojandy/sjb-pkg-repo/master"
NOTIFY_TITLE=coding-at-sjb

# make directories and its symbolic links
mkdir -p $SJB_HOME/usr
mkdir -p $SJB_HOME/Downloads
mkdir -p $SJB_HOME/Projects
ln -sf $SJB_HOME/dotfiles $DOTFILES
rmdir $HOME/다운로드 && ln -sf $SJB_HOME/Downloads $HOME/다운로드
ln -sf $HOME/다운로드 $HOME/Downloads
ln -sf $SJB_HOME/Projects $HOME/Projects

# install configs
git clone https://github.com/kojandy/.dotfiles /tmp/sjb/dotfiles
ln -sf $DOTFILES/profile $HOME/.profile
mkdir -p $XDG_CONFIG_HOME/nvim
ln -sf $DOTFILES/nvim/init.vim $XDG_CONFIG_HOME/nvim/init.vim
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc
mkdir -p $XDG_CONFIG_HOME/git
ln -sf $DOTFILES/git/config $XDG_CONFIG_HOME/git/config
ln -sf $DOTFILES/git/ignore $XDG_CONFIG_HOME/git/ignore
mkdir -p $XDG_CONFIG_HOME/spectrwm
ln -sf $HOME/.dotfiles/spectrwm/spectrwm.conf $XDG_CONFIG_HOME/spectrwm/spectrwm.conf
mkdir -p $HOME/.config/picom
ln -sf $HOME/.dotfiles/picom/picom.conf $HOME/.config/picom/picom.conf
mkdir -p $XDG_CONFIG_HOME/alacritty
ln -sf $DOTFILES/alacritty/alacritty.yml $XDG_CONFIG_HOME/alacritty/alacritty.yml
mkdir -p $XDG_CONFIG_HOME/dunst
ln -sf $DOTFILES/dunst/dunstrc $XDG_CONFIG_HOME/dunst/dunstrc

# map caps lock to control
echo "remove Lock = Caps_Lock
keysym Caps_Lock = Control_L
add Control = Control_L" > $HOME/.xmodmap
xmodmap $HOME/.xmodmap

# setup desktop environment
setsid sh -c "
    curl '$REPO_URL/spectrwm.tar.xz' | tar -xJ -C $SJB_HOME &
    curl '$REPO_URL/dmenu.tar.xz' | tar -xJ -C $SJB_HOME &
    curl '$REPO_URL/picom.tar.xz' | tar -xJ -C $SJB_HOME &
    curl '$REPO_URL/dunst.tar.xz' | tar -xJ -C $SJB_HOME &
    wait

    gsettings set org.nemo.desktop show-desktop-icons false
    gsettings set org.cinnamon.desktop.background picture-uri 'file:///usr/share/backgrounds/linuxmint-tara/rsmith_single_blade_of_grass.jpg'

    pkill -x cinnamon
    pkill Hamonize-pcmngr

    sleep 0.1

    export PATH=$SJB_HOME/usr/bin:$PATH
    export LD_LIBRARY_PATH=$SJB_HOME/usr/lib
    cd $HOME
    . $HOME/.profile
    setsid spectrwm >/dev/null 2>&1 &
    setsid picom &
    setsid dunst &

    sleep 0.1

    notify-send -u low '$NOTIFY_TITLE' 'Desktop environment setup completed!'
" &

# install fonts
setsid sh -c "
    mkdir -p '$HOME/.local/share/fonts'
    curl -L 'https://github.com/tonsky/FiraCode/blob/master/distr/ttf/FiraCode-Regular.ttf?raw=true' -o '$HOME/.local/share/fonts/FiraCode-Regular.ttf' &
    curl -L 'https://github.com/tonsky/FiraCode/blob/master/distr/ttf/FiraCode-Bold.ttf?raw=true' -o '$HOME/.local/share/fonts/FiraCode-Bold.ttf' &
    wait
    fc-cache -f
    pkill -HUP spectrwm && pkill -QUIT code
" &

# install zsh
setsid sh -c "
    curl '$REPO_URL/zsh.tar.xz' | tar -xJ -C $SJB_HOME
    $SJB_HOME/usr/bin/zsh -c 'source ~/.zshrc && exit'
    $HOME/.zgen/romkatv/powerlevel10k-master/gitstatus/install
    echo 'exec $SJB_HOME/usr/bin/zsh' > $HOME/.bashrc
    notify-send '$NOTIFY_TITLE' 'zsh Installed!'
" &

# install alacritty
setsid sh -c "
    curl '$REPO_URL/alacritty.tar.xz' | tar -xJ -C $SJB_HOME
    notify-send -u low '$NOTIFY_TITLE' 'alacritty Installed!'
" &

# install neovim
setsid sh -c "
    curl 'https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.xz' | tar -xJ --strip-components=1 -C $SJB_HOME/usr &
    curl -L 'https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz' | tar -xz --strip-components=1 -C $SJB_HOME/usr &
    wait
    $SJB_HOME/usr/bin/nvim +PlugInstall +qa
    $SJB_HOME/usr/bin/nvim '+CocInstall -sync coc-actions coc-git coc-yank' +qa
    notify-send '$NOTIFY_TITLE' 'neovim Installed!'
" &
