#!/bin/sh
SJB_HOME=/tmp/sjb
DOTFILES=$HOME/.dotfiles
XDG_CONFIG_HOME=$HOME/.config
REPO_URL="https://raw.githubusercontent.com/kojandy/sjb-pkg-repo/master"
NOTIFY_TITLE=coding-at-sjb

# make directories and its symbolic links
mkdir -p $SJB_HOME/usr
mkdir -p $SJB_HOME/Downloads
mkdir -p $SJB_HOME/Projects
sed -i 's/다운로드/Downloads/' $XDG_CONFIG_HOME/user-dirs.dirs
ln -sf $SJB_HOME/dotfiles $DOTFILES
ln -sf $SJB_HOME/Downloads $HOME/Downloads
ln -sf $SJB_HOME/Projects $HOME/Projects
rm -rf $HOME/공개 $HOME/문서 $HOME/사진 $HOME/음악 $HOME/비디오 $HOME/템플릿 $HOME/다운로드

# install configs
git clone https://github.com/kojandy/.dotfiles /tmp/sjb/dotfiles
ln -sf $DOTFILES/profile $HOME/.profile
mkdir -p $XDG_CONFIG_HOME/nvim
ln -sf $DOTFILES/nvim/init.vim $XDG_CONFIG_HOME/nvim/init.vim
ln -sf $DOTFILES/nvim/lua $XDG_CONFIG_HOME/nvim/lua
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc
mkdir -p $XDG_CONFIG_HOME/git
ln -sf $DOTFILES/git/config $XDG_CONFIG_HOME/git/config
ln -sf $DOTFILES/git/ignore $XDG_CONFIG_HOME/git/ignore
mkdir -p $HOME/.config/picom
ln -sf $HOME/.dotfiles/picom/picom.conf $HOME/.config/picom/picom.conf
mkdir -p $XDG_CONFIG_HOME/alacritty
ln -sf $HOME/coding-at-sjb/config/alacritty/alacritty.yml $XDG_CONFIG_HOME/alacritty/alacritty.yml
mkdir -p $XDG_CONFIG_HOME/awesome
ln -sf $HOME/coding-at-sjb/config/awesome/rc.lua $XDG_CONFIG_HOME/awesome/rc.lua
mkdir -p $HOME/.config/lf
ln -sf $HOME/.dotfiles/lf/lfrc $HOME/.config/lf/lfrc

# map caps lock to control
echo "remove Lock = Caps_Lock
keysym Caps_Lock = Control_L
add Control = Control_L" > $HOME/.xmodmap
xmodmap $HOME/.xmodmap

# unmute everything
amixer set Front unmute && amixer set Headphone 100% unmute && amixer set Master 45% unmute

# setup desktop environment
setsid sh -c "
    curl '$REPO_URL/awesome.tar.xz' | tar -xJ -C $SJB_HOME &
    curl '$REPO_URL/picom.tar.xz' | tar -xJ -C $SJB_HOME &
    wait

    git clone https://github.com/kojandy/awesome-wm-nice $SJB_HOME/awesome/lib/nice

    gsettings set org.nemo.desktop show-desktop-icons false
    gsettings set org.cinnamon.desktop.background picture-uri 'file:///usr/share/backgrounds/linuxmint-tara/evablue_jacques_cartier.jpg'

    pkill -x cinnamon
    pkill Hamonize-pcmngr

    sleep 0.1

    export PATH=$SJB_HOME/usr/bin:$PATH
    export LD_LIBRARY_PATH=$SJB_HOME/usr/lib
    cd $HOME
    . $HOME/.profile

    until awesome
    do
        cd $HOME/coding-at-sjb
        git reset --hard
        cd $HOME
        sleep 1
    done
" &

# install fonts
setsid sh -c "
    mkdir -p '$HOME/.local/share/fonts'
    curl -L '$REPO_URL/fonts.tar.xz' | tar -xJ -C '$HOME/.local/share/fonts'
    fc-cache -f
" &

# install zsh
setsid sh -c "
    curl '$REPO_URL/zsh.tar.xz' | tar -xJ -C $SJB_HOME
    $SJB_HOME/usr/bin/zsh -c 'source ~/.zshrc && exit'
    $HOME/.zgen/romkatv/powerlevel10k-master/gitstatus/install
    echo 'exec $SJB_HOME/usr/bin/zsh' > $HOME/.bashrc
    notify-send '$NOTIFY_TITLE' 'zsh Installed!'
" &

# install alacritty
setsid sh -c "
    curl '$REPO_URL/alacritty.tar.xz' | tar -xJ -C $SJB_HOME
    notify-send -u low '$NOTIFY_TITLE' 'alacritty Installed!'
" &

# install neovim
setsid sh -c "
    curl 'https://nodejs.org/dist/v15.8.0/node-v15.8.0-linux-x64.tar.xz' | tar -xJ --strip-components=1 -C $SJB_HOME/usr &
    curl -L 'https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage' -o $SJB_HOME/usr/bin/nvim
    wait
    chmod +x $SJB_HOME/usr/bin/nvim
    $SJB_HOME/usr/bin/nvim --appimage-extract
    mv squashfs-root $SJB_HOME/usr/bin/nvim-root
    ln -sf $SJB_HOME/usr/bin/nvim-root/AppRun $SJB_HOME/usr/bin/nvim
    $SJB_HOME/usr/bin/nvim +PlugInstall +qa >/dev/null 2>&1
    notify-send '$NOTIFY_TITLE' 'neovim Installed!'
" &

# install etcs
setsid sh -c "
    curl -L 'https://github.com/altdesktop/playerctl/releases/download/v2.3.1/playerctl-2.3.1_amd64.deb' | dpkg -x /dev/stdin /tmp/sjb &
    $DOTFILES/install/lf &
    $DOTFILES/install/rg &
    wait
" &
