#!/bin/sh
echo "export PATH=/tmp/sjb/junest/bin:\$PATH
export JUNEST_HOME=/tmp/sjb/junest/home" >> $HOME/.zshrc.local
git clone https://github.com/fsquillace/junest /tmp/sjb/junest
mkdir -p /tmp/sjb/junest/home
wget 'http://dodo.kojandy.com/home.tar.xz' -O /tmp/sjb/junest/home.tar.xz
tar -xf /tmp/sjb/junest/home.tar.xz -C /tmp/sjb/junest/home
