#!/bin/sh
SCRIPT=$(mktemp --tmpdir XXX.sh)
curl 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh' -o "$SCRIPT"
sh "$SCRIPT" -bp '/tmp/sjb/python'
rm "$SCRIPT"
echo 'eval "$('"'/tmp/sjb/python/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)\"" >> $HOME/.zshrc.local
