#!/bin/sh
curl -L 'https://github.com/radareorg/radare2/releases/download/4.5.1/radare2-ubuntu-1804_4.5.1_amd64.deb' |
    dpkg -x - /tmp/sjb/radare2
echo 'export PATH=/tmp/sjb/radare2/usr/bin:$PATH' >> $HOME/.zshrc.local
echo 'export LD_LIBRARY_PATH=/tmp/sjb/radare2/usr/lib:$LD_LIBRARY_PATH' >> $HOME/.zshrc.local
