#!/bin/sh

curl -L# 'https://github.com/BurntSushi/ripgrep/releases/download/12.1.0/ripgrep-12.1.0-x86_64-unknown-linux-musl.tar.gz' | \
    tar -xz -C /tmp/sjb/usr/bin --strip-components=1 'ripgrep-12.1.0-x86_64-unknown-linux-musl/rg'
