#!/bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 10
bspc config border_width 1

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer true

bspc config normal_border_color "#878787"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#fedc56"
